apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: owahed1/go-lang-app:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000 
  type: LoadBalancer
